# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed

markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : mfairchild365

author :
  name : Michael Fairchild
  email : mfairchild@unl.edu
  github : mfairchild365
  twitter : mfairchild365
  #feedburner : feedname

baseurl : '/'
